# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://117.72.199.193:5432/my_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=JEp:beRx!ZS!Pj3

# PostgreSQL connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Always execute schema.sql (not only for embedded databases)
spring.sql.init.mode=always
