    -- 系统用户表
    CREATE TABLE IF NOT EXISTS sys_user (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- 主键ID
        email VARCHAR(255) NOT NULL UNIQUE,                           -- 用户邮箱（登录账号）
        password VARCHAR(255) NOT NULL,                               -- 登录密码（加密存储）
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                -- 注册时间
    );

    -- 文档表
    CREATE TABLE IF NOT EXISTS doc_document (
        id VARCHAR(36) PRIMARY KEY,                                   -- 主键ID（UUID）
        name VARCHAR(500) NOT NULL,                                   -- 文档名称
        type VARCHAR(20) NOT NULL,                                    -- 文件类型（txt, md, pdf, docx）
        size BIGINT NOT NULL DEFAULT 0,                               -- 文件大小（字节）
        file_path VARCHAR(1000) NOT NULL,                             -- 文件存储路径
        user_id VARCHAR(255) NOT NULL,                                -- 上传用户ID（邮箱）
        is_public BOOLEAN NOT NULL DEFAULT FALSE,                     -- 是否公共文档
        chunk_count INTEGER NOT NULL DEFAULT 0,                       -- 文档分块数量
        status VARCHAR(20) NOT NULL DEFAULT 'PENDING',                -- 处理状态（PENDING/PROCESSING/COMPLETED/FAILED）
        upload_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP               -- 上传时间
    );

    -- 索引：按用户查询文档
    CREATE INDEX IF NOT EXISTS idx_doc_document_user_id ON doc_document(user_id);
    -- 索引：按公开状态查询文档
    CREATE INDEX IF NOT EXISTS idx_doc_document_is_public ON doc_document(is_public);

    -- sys_user 表注释
    COMMENT ON TABLE sys_user IS '系统用户表';
    COMMENT ON COLUMN sys_user.id IS '主键ID';
    COMMENT ON COLUMN sys_user.email IS '用户邮箱（登录账号）';
    COMMENT ON COLUMN sys_user.password IS '登录密码（加密存储）';
    COMMENT ON COLUMN sys_user.created_at IS '注册时间';

    -- doc_document 表注释
    COMMENT ON TABLE doc_document IS '文档表';
    COMMENT ON COLUMN doc_document.id IS '主键ID（UUID）';
    COMMENT ON COLUMN doc_document.name IS '文档名称';
    COMMENT ON COLUMN doc_document.type IS '文件类型（txt, md, pdf, docx）';
    COMMENT ON COLUMN doc_document.size IS '文件大小（字节）';
    COMMENT ON COLUMN doc_document.file_path IS '文件存储路径';
    COMMENT ON COLUMN doc_document.user_id IS '上传用户ID（邮箱）';
    COMMENT ON COLUMN doc_document.is_public IS '是否公共文档';
    COMMENT ON COLUMN doc_document.chunk_count IS '文档分块数量';
    COMMENT ON COLUMN doc_document.status IS '处理状态（PENDING/PROCESSING/COMPLETED/FAILED）';
    COMMENT ON COLUMN doc_document.upload_time IS '上传时间';
